### ISSUE TITLE
Error Could not connect to the appstore or the appstore returned no updates at all

### ISSUE THREAD

**Issue by ghost** [nextcloud/caniupdate#12]
Getting below error. My server has access to the internet i don't see any issues on the server end. 
![image](https://user-images.githubusercontent.com/24574019/33733138-63f0c92e-db4e-11e7-95b1-b4b9af27bdad.png)

**Comment by nickvergessen** [comment]
Can you check your nextcloud.log file whether it has related entries?

**Comment by ghost** [comment]
no it dosen't no longs on it

**Comment by Mgldvd** [comment]
Same here Nextcloud 12

**Comment by bowmasters** [comment]
I had the same error on Nextcloud 12. In my case, the ajax request to `applist` was returning a 404 due to an empty `$availableApps` array.

If anyone else's case is like mine, here's what I did:

I found I had incorrect ownership on _future-apps.json_ (was "root" instead of "www-data") which made `get()` return an empty array when the fetcher threw an exception trying to write to the file.

But it looks there was also some sort of caching issue since fixing ownership alone didn't solve the problem for me. Even manually recreating and deleting the file and its parent had no effect; the call to `getFile()`_(Fetcher.php:137)_ acted like the file still existed and instantiated a `SimpleFile` object (pointing to a non-existing file) instead of throwing a `NotFoundException` and triggering file creation.

I inadvertently fixed the problem in the course of troubleshooting (basically forced a NotFoundException) and everything worked fine after that. 

I'm unfamiliar with the inner workings of Nextcloud and the OC files library, but I assume there's a more straightforward way to update the files cache that I just don't know about. Presumably, rebooting would work too, but I couldn't test this.

**Comment by nickvergessen** [comment]
Thanks for the debugging effort! @bowmasters 

Well deleting a file on the filesystem is not complete, yes. The information is also stored in the oc_filecache table (which is no cache but an index), so that explains why it didn't fail at first. I surely can add code to check for empty content (which I should receive in case of wrong chmod/chown), but not sure if the app should have to do this.

**Comment by bowmasters** [comment]
Agreed, this seems to be a problem outside the scope of the app. Namely, we should fix the way exceptions are handled upstream in Fetcher.php's get(). Right now, the blanket catch-all block just returns an empty array without logging anything. At the very least, logging the exception would help with debugging.

**Comment by nickvergessen** [comment]
Logging will be fixed with the next set of releases:
https://github.com/nextcloud/server/pull/8474
